### ISSUE TITLE
vmを借りる

### ISSUE THREAD

**Issue by AnaTofuZ** [AnaTofuZ/ie-openmpi-E-2017#1]
### 借りて!!!

**Comment by AnaTofuZ** [comment]
- 10コア
- 8GB
- シス感に連絡(cc.名嘉村先生)

**Comment by KaitoIshizuka** [comment]
155716F 石塚です。
並列分散処理の講義でコア数の多いVMを使う必要があるので
VMの作成を依頼したいです。
VMのスペックは
====================
OS:Fedora24
メモリ:8GB
コア数:10コア
ハードドライブサイズ:20GB
====================
です。
以上宜しくお願いします。

送った
