### ISSUE TITLE
素数を求めるプログラムをシュッと書く

### ISSUE THREAD

**Issue by AnaTofuZ** [AnaTofuZ/ie-openmpi-E-2017#4]
- 並列化
- ふつうの奴

比較する!!!やるお!!!

**Comment by YOGIyoshiya** [comment]
http://www.tsg.ne.jp/TT/tsg/c/mansaku/P01.html
参考にしたところ

**Comment by YOGIyoshiya** [comment]
基本的なプログラムは完成した

**Comment by YOGIyoshiya** [comment]
http://auewe.hatenablog.com/entry/2013/10/16/054345
parallel forについて

**Comment by AnaTofuZ** [comment]
https://docs.oracle.com/cd/E19205-01/820-1217/aewbc/index.html

**Comment by YOGIyoshiya** [comment]
http://www.cms-initiative.jp/ja/events/20130425katagiri.pdf
private関連
